"""baseline

Revision ID: f2290511537e
Revises: 
Create Date: 2026-05-07 20:30:27.258470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2290511537e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pg_owners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pg_name', sa.String(length=120), nullable=False),
    sa.Column('owner_name', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('upi_vpa', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pg_owners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pg_owners_phone_number'), ['phone_number'], unique=True)

    op.create_table('notices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.Column('delivered_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('pg_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pg_id'], ['pg_owners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notices_pg_id'), ['pg_id'], unique=False)

    op.create_table('rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=False),
    sa.Column('total_capacity', sa.Integer(), nullable=False),
    sa.Column('pg_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('total_capacity > 0', name='ck_rooms_capacity_positive'),
    sa.ForeignKeyConstraint(['pg_id'], ['pg_owners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pg_id', 'room_number', name='uq_rooms_pg_room_number')
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rooms_pg_id'), ['pg_id'], unique=False)

    op.create_table('residents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('monthly_rent', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('security_deposit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('joined_date', sa.Date(), nullable=False),
    sa.Column('move_out_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('pg_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('monthly_rent >= 0', name='ck_residents_rent_nonneg'),
    sa.CheckConstraint('security_deposit >= 0', name='ck_residents_deposit_nonneg'),
    sa.ForeignKeyConstraint(['pg_id'], ['pg_owners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('residents', schema=None) as batch_op:
        batch_op.create_index('ix_residents_pg_active', ['pg_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_residents_pg_id'), ['pg_id'], unique=False)
        batch_op.create_index('ix_residents_pg_phone', ['pg_id', 'phone_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_residents_room_id'), ['room_id'], unique=False)

    op.create_table('complaints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=True),
    sa.Column('raw_whatsapp_msg', sa.Text(), nullable=False),
    sa.Column('parsed_issue', sa.Text(), nullable=True),
    sa.Column('room_number', sa.String(length=20), nullable=True),
    sa.Column('category', sa.Enum('plumbing', 'electrical', 'cleaning', 'appliance', 'security', 'internet', 'other', name='complaint_category'), nullable=False),
    sa.Column('urgency', sa.Enum('low', 'medium', 'high', name='complaint_urgency'), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=80), nullable=True),
    sa.Column('pg_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pg_id'], ['pg_owners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_message_id')
    )
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaints_pg_id'), ['pg_id'], unique=False)
        batch_op.create_index('ix_complaints_pg_resolved', ['pg_id', 'is_resolved'], unique=False)
        batch_op.create_index('ix_complaints_pg_urgency', ['pg_id', 'urgency'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_resident_id'), ['resident_id'], unique=False)

    op.create_table('ledger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('month_year', sa.String(length=7), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transaction_ref_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('pending', 'partial', 'paid', name='ledger_status'), nullable=False),
    sa.Column('pg_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount_due >= 0', name='ck_ledger_due_nonneg'),
    sa.CheckConstraint('amount_paid >= 0', name='ck_ledger_paid_nonneg'),
    sa.ForeignKeyConstraint(['pg_id'], ['pg_owners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pg_id', 'resident_id', 'month_year', name='uq_ledger_resident_month')
    )
    with op.batch_alter_table('ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_pg_id'), ['pg_id'], unique=False)
        batch_op.create_index('ix_ledger_pg_month', ['pg_id', 'month_year'], unique=False)
        batch_op.create_index('ix_ledger_pg_status', ['pg_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_resident_id'), ['resident_id'], unique=False)

    op.create_table('meal_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('prompted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('will_eat_dinner', sa.Boolean(), nullable=True),
    sa.Column('special_instructions', sa.String(length=500), nullable=True),
    sa.Column('pg_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pg_id'], ['pg_owners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pg_id', 'resident_id', 'date', name='uq_meal_logs_resident_date')
    )
    with op.batch_alter_table('meal_logs', schema=None) as batch_op:
        batch_op.create_index('ix_meal_logs_pg_date', ['pg_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_logs_pg_id'), ['pg_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_logs_resident_id'), ['resident_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_logs_resident_id'))
        batch_op.drop_index(batch_op.f('ix_meal_logs_pg_id'))
        batch_op.drop_index('ix_meal_logs_pg_date')

    op.drop_table('meal_logs')
    with op.batch_alter_table('ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_resident_id'))
        batch_op.drop_index('ix_ledger_pg_status')
        batch_op.drop_index('ix_ledger_pg_month')
        batch_op.drop_index(batch_op.f('ix_ledger_pg_id'))

    op.drop_table('ledger')
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaints_resident_id'))
        batch_op.drop_index('ix_complaints_pg_urgency')
        batch_op.drop_index('ix_complaints_pg_resolved')
        batch_op.drop_index(batch_op.f('ix_complaints_pg_id'))

    op.drop_table('complaints')
    with op.batch_alter_table('residents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_residents_room_id'))
        batch_op.drop_index('ix_residents_pg_phone')
        batch_op.drop_index(batch_op.f('ix_residents_pg_id'))
        batch_op.drop_index('ix_residents_pg_active')

    op.drop_table('residents')
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rooms_pg_id'))

    op.drop_table('rooms')
    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notices_pg_id'))

    op.drop_table('notices')
    with op.batch_alter_table('pg_owners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pg_owners_phone_number'))

    op.drop_table('pg_owners')
    # ### end Alembic commands ###
